### ISSUE TITLE
Bootcamp Feedback

### ISSUE THREAD

**Issue by andrew-bortvin** [squidtwopointward/qbb2023-answers#1]
# Grading 

## Day 1 Homework 

**5.5/6**

| Exercise    | Task  | Grade |
| -------- | ------- | ------- |
| E1  | Printed out first, tenth, last days  |  1|
| E2 | Calculated averages for all patients  | 1 | 
| E2   | Printed out first ten averages   |1  |
| E3 | Printed out maximum |1 | 
| E3 | Printed out minimum | 1| 
| E4 | Printed out differences between patients |0.5|

I think that in exercise 2, line 36, `all += day_int` should be indented one more level so that it runs every iteration of the for loop. Hard to be sure without seeing output. You have the right idea here - just something to keep in mind for the future. 

For exercise 4, you sum all days together and find the difference (so the difference in total for all days). We ask to find the difference for each day (i.e. print patient 1, day 1 - patient 2, day 1, and so on for all days). **Modify this one for full credit.** 

## Day 2 Homework:  

**6/7**

| Exercise    | Task  | Grade |
| -------- | ------- | ------- |
| E1  | Plot female data | 1 |
| E1  | Add male data |1  |
| E1  | Plotted two x male data |  1|
| E1  | Added x axis label |1  |
| E1  | Added y axis label | 1 |
| E1  | Labelled each line using a legend | 0 |
| E1  | Added plot title | 1 |

Add a legend and this'll be perfect! 

## Day 3 Homework: 

**6/6**

| Exercise    | Task  | Grade |
| -------- | ------- | ------- |
| E1  | `mean.py` calculates means |  1 |
| E2  | `mean_from_file.py` reads in file and calculates means | 1 |
| E3  | `mean_inflammation.py` contains function that calculates mean inflammation | 1  |
| E3  | `mean_inflammation.py` prints output | 1 |
| E4  | `difference_inflammation.py` contains function that calculates the difference in inflammation | 1 |
| E4  | `difference_inflammation.py` prints output | 1 | 

## Day 4 Homework: 

**6/10**

| Exercise    | Task  | Grade |
| -------- | ------- | ------- |
| E1  | Created a function to simulate WF | 1  |
| E1  | Find the number of generations to fixation | 1 |
| E1  | Plot of allele frequency over time | 0 |
| E2  | Plot of allele frequency over time for multiple alleles | 0 |
| E2  | Histogram of times to fixation | 0 |
| E3  | Plot of population size vs time to fixation | 0 |
| E3  | Plot of starting allele frequency vs time to fixation | 0 |
| E4  | Short written answers to three questions |  1 |

Really good start! Your wright fisher function looks great. Please add the following: 

* Your code mostly looks good. A quick notes:
    * For exercise 2, when you try to add lines to a plot using a `for` loop, you should indent the `plot` line so that it is part of your code 
* Upload all of your plots
* Short answers for exercise 4

**Comment by andrew-bortvin** [comment]
Edited to reflect inclusion of a short answer for WF exercise 4. 

Please upload the following:
* images of your plots for the Wright Fisher assignment. The code I can see looks good.
* I only found an answer to one short question. Add two more (or please point me to where I can find them if they're up already and I'm missing it) for full credit.

**Comment by squidtwopointward** [comment]
Uploaded
